version: "3"
services:
  mysqld:
    image: mysql:5.7
    container_name: mysqld
    restart: always
    ports:
      - "3307:3306"
    networks:
      - database
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: "Asia/Seoul"
    volumes:
      # - mysql-data:/var/lib/data/mysql
      # - ./postgresql:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    restart: always
    ports:
      - 3095:3095
    depends_on:
      - mysqld
    networks:
      - database
      - frontApp
    # volumes:
    #   - ./back:/usr/src/app

  # front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   container_name: front
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - back
  #   networks:
  #     - frontApp

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/log:/var/log/nginx
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./www:/var/www/html
  #   depends_on:
  #     - back
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - frontApp

  # certbot:
  #   depends_on:
  #     - nginx
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #     - ./www:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email ydngjink1234@gmail.com --agree-tos --no-eff-email --force-renewal -d stylelint1.ml -d www.stylelint1.ml

# volumes:
#   mysql-data:

networks:
  database:
    driver: bridge
  frontApp:
    driver: bridge
